analogdevicesinc/ai8x-training

datasets/kws20.py
Overlaped data option is added for data folding into 2D structure. Added mu-law companding.
=> refactor kws20 dataset generation code.

ai8x.py, models/ai85net-nas-cifar.py, qat_policy_late_cifar.yaml, schedule-cifar-nas.yaml, scripts/evaluate_cifar10.sh, scripts/evaluate_cifar100.sh, scripts/train_cifar10.sh, scripts/train_cifar100_qat8.sh, train.py
Add Cifar10, Cifar100 models found by NAS
Add bias into output shift calculations
Add quantile parameter for output shift calculations
=> Fix regression issue by changing ceil to floor

README.md, train.py
* Suppress default parameter warning for evaluation mode
=> README: Clarify models and dataset structures, model instantiation and parameters

ai8x.py
ai8x.py is modified to calculate the floor value of the average pooling
layer matching with the value of the hardware simulator.
See pool1d and pool2d function implementations in
"ai8x-synthesis/izer/compute.py" for the floor operation implementation
in average pooling in the simulator.
=> Fix model value for average pooling with floor

datasets/camvid.py
Fixes the issue in the refactored code in commit #120.
=> CamVid dataloader bug fix

parsecmd.py, train.py
Training script is fixed not to search for object detection parameters
file for other types of training.
Training script is modified to properly pass device parameter to object
detection models explicitly.
=> Fix train script for object detection parameters

TensorFlow/ai8xTF.py
I was having some dynamic range trouble while training my AI8x model with TensorFlow and needed to make use of the output_shift parameter in the 2nd to last dense layer.  The addition of the quantize layer seemed straightforward enough, but given it was intentionally left empty I'm guessing there's more going on here than meets the eye.
Here's the network definition:
```
layers:
- pad: 0
activate: ReLU
out_offset: 0x2000
processors: 0x0000000000000001
data_format: CHW
op: conv2d
- pad: 0
activate: ReLU
out_offset: 0
processors: 0xffffffff00000000
op: conv2d
- max_pool: 2
pool_stride: 2
pad: 0
out_offset: 0x2000
processors: 0xffffffffffffffff
op: none
- op: mlp
activate: ReLU
flatten: true
out_offset: 0
output_shift: -3
processors: 0xffffffffffffffff
- op: mlp
flatten: true
out_offset: …
```
=> implement output_shift layer parameter/add quantization layer

ai8x.py
changes update line of the parameter output_shift
=> Changing how `output_shift` is updated

ai8x.py
Default value for stride is changed as 1.
Solves Issue #194.
=> Update Conv1d Initializer

scripts/evaluate_svhn_tinierssd.sh, train.py
The validation function is fixed for the case when --save-sample option was selected in train.py.
=> Fix train.py for saving sample npy

README.md, ai8x.py, datasets/aisegment.py, datasets/camvid.py, models/ai85net-unet.py, parsecmd.py, scripts/evaluate_aisegment_unet.sh, scripts/evaluate_camvid_unet.sh, scripts/train_aisegment_unet.sh, scripts/train_camvid_unet.sh, train.py
- Folding added as a dataset transformation
- Unfolding function added and called in train.py when required
- UNET models updated
- CamVid and AISegmnet datasets updated to call new folding transformation
=> Remove data folding from model architecture

ai8x.py
Replaces python operations with torch exp/mul/div operations for tensors. This provides ~10% speed up in model training.
=> Refactor tensor operations

scripts/train_svhn_tinierssd.sh, train.py
Disabled PR curve generation for object detection models. Solves #215.
=> PR Curve generation disabled for object detection

README.md, losses/multiboxloss.py, train.py, utils/object_detection_utils.py
Multi-box loss and evaluation parts of training is modified for improved stability in object detection model trainings.
Modifications include fixes for the case where batch is full of data samples with no objects, the case where model priors or object boxes have some zero height or widths and the case where no object boxes can be assigned to any model prior boxes (see multi box loss for details).
Data loaders/models are also suggested to prevent zero height or width boxes as they are not realistic.
Still nan or inf values  has to be prevented for multi-box loss or mAP as one of those disrupts all statistics.
=> Improve stability of training for detection models

train.py
Assertion in train.py fixed to check the train, validation and test data loaders according to be in train or evaluate mode
Solves #239
=> Improve check for required Data Loaders

.yamllint, NOTICE.txt
=> Add NOTICE

README.md, requirements.txt
Hawk-eyes version reduced to support macOS. Replacing hawk-eyes with another detector is in near future plan.
Documentation update for recently added command-line arguments.
=> Improve compatibility and documentation

scripts/evaluate_mobilefacenet_112.sh
Fixes checkpoint name for the evaluate_mobilefacenet_112.sh.
=> Fix eval ckpt naming for ai87netmobilefacenet_112

datasets/kws20.py
Fixes https://github.com/analogdevicesinc/ai8x-training/issues/316
=> Fix issues with unquantized KWS dataset; add quantized KWS_35

datasets/vggface2.py, requirements.txt, train.py
1- Similar to the  [1.8](https://github.com/analogdevicesinc/ai8x-training/pull/320) replacement, face-detection library has been changed with the batch-face.
2- Added the missing parts of relation-based knowledge distillation from 1.8.
=> Replace Face Detection Library
